namespace :spy_game do
  task build_game_role: :environment do
    SpyGameRole.create([place: '飛機', name: '頭等艙乘客'])
    SpyGameRole.create([place: '飛機', name: '空軍中將'])
    SpyGameRole.create([place: '飛機', name: '機械工'])
    SpyGameRole.create([place: '飛機', name: '經濟艙乘客'])
    SpyGameRole.create([place: '飛機', name: '空姐'])
    SpyGameRole.create([place: '飛機', name: '副駕駛'])
    SpyGameRole.create([place: '飛機', name: '機長'])

    SpyGameRole.create([place: '銀行', name: '武裝車駕駛'])
    SpyGameRole.create([place: '銀行', name: '經理'])
    SpyGameRole.create([place: '銀行', name: '顧問'])
    SpyGameRole.create([place: '銀行', name: '顧客'])
    SpyGameRole.create([place: '銀行', name: '強盜'])
    SpyGameRole.create([place: '銀行', name: '警衛'])
    SpyGameRole.create([place: '銀行', name: '行員'])

    SpyGameRole.create([place: '海灘', name: '服務生'])
    SpyGameRole.create([place: '海灘', name: '風帆衝浪者'])
    SpyGameRole.create([place: '海灘', name: '救生員'])
    SpyGameRole.create([place: '海灘', name: '小偷'])
    SpyGameRole.create([place: '海灘', name: '海灘遊客'])
    SpyGameRole.create([place: '海灘', name: '冰淇淋車駕駛'])
    SpyGameRole.create([place: '海灘', name: '攝影師'])

    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])
    SpyGameRole.create([place: '嘉年華會', name: '頭等艙乘客'])

    SpyGameRole.create([place: '賭場', name: '酒保'])
    SpyGameRole.create([place: '賭場', name: '警衛'])
    SpyGameRole.create([place: '賭場', name: '保鑣'])
    SpyGameRole.create([place: '賭場', name: '經理'])
    SpyGameRole.create([place: '賭場', name: '騙子'])
    SpyGameRole.create([place: '賭場', name: '發牌員'])
    SpyGameRole.create([place: '賭場', name: '賭徒'])

    SpyGameRole.create([place: '馬戲團', name: '特技演員'])
    SpyGameRole.create([place: '馬戲團', name: '動物訓練師'])
    SpyGameRole.create([place: '馬戲團', name: '魔術師'])
    SpyGameRole.create([place: '馬戲團', name: '觀眾'])
    SpyGameRole.create([place: '馬戲團', name: '吞火者'])
    SpyGameRole.create([place: '馬戲團', name: '小丑'])
    SpyGameRole.create([place: '馬戲團', name: '雜耍者'])

    SpyGameRole.create([place: '企業派對', name: '藝人'])
    SpyGameRole.create([place: '企業派對', name: '經理'])
    SpyGameRole.create([place: '企業派對', name: '不請自來的人'])
    SpyGameRole.create([place: '企業派對', name: '老闆'])
    SpyGameRole.create([place: '企業派對', name: '秘書'])
    SpyGameRole.create([place: '企業派對', name: '會計'])
    SpyGameRole.create([place: '企業派對', name: '送貨小弟'])

    SpyGameRole.create([place: '十字軍軍團', name: '僧侶'])
    SpyGameRole.create([place: '十字軍軍團', name: '囚犯'])
    SpyGameRole.create([place: '十字軍軍團', name: '僕人'])
    SpyGameRole.create([place: '十字軍軍團', name: '主教'])
    SpyGameRole.create([place: '十字軍軍團', name: '騎士'])
    SpyGameRole.create([place: '十字軍軍團', name: '護衛'])
    SpyGameRole.create([place: '十字軍軍團', name: '弓箭手'])

    SpyGameRole.create([place: 'SPA中心', name: '顧客'])
    SpyGameRole.create([place: 'SPA中心', name: '造型師'])
    SpyGameRole.create([place: 'SPA中心', name: '女按摩師'])
    SpyGameRole.create([place: 'SPA中心', name: '皮膚顧問'])
    SpyGameRole.create([place: 'SPA中心', name: '化妝師'])
    SpyGameRole.create([place: 'SPA中心', name: '美甲師'])
    SpyGameRole.create([place: 'SPA中心', name: '美容師'])

    SpyGameRole.create([place: '大使館', name: '警衛'])
    SpyGameRole.create([place: '大使館', name: '秘書'])
    SpyGameRole.create([place: '大使館', name: '大使'])
    SpyGameRole.create([place: '大使館', name: '公務人員'])
    SpyGameRole.create([place: '大使館', name: '遊客'])
    SpyGameRole.create([place: '大使館', name: '難民'])
    SpyGameRole.create([place: '大使館', name: '外交官'])

    SpyGameRole.create([place: '醫院', name: '護士'])
    SpyGameRole.create([place: '醫院', name: '醫生'])
    SpyGameRole.create([place: '醫院', name: '麻醉師'])
    SpyGameRole.create([place: '醫院', name: '實習醫生'])
    SpyGameRole.create([place: '醫院', name: '病患'])
    SpyGameRole.create([place: '醫院', name: '心理治療師'])
    SpyGameRole.create([place: '醫院', name: '外科醫生'])

    SpyGameRole.create([place: '旅館', name: '門衛'])
    SpyGameRole.create([place: '旅館', name: '警衛'])
    SpyGameRole.create([place: '旅館', name: '經理'])
    SpyGameRole.create([place: '旅館', name: '清潔人員'])
    SpyGameRole.create([place: '旅館', name: '顧客'])
    SpyGameRole.create([place: '旅館', name: '酒保'])
    SpyGameRole.create([place: '旅館', name: '行李小弟'])

    SpyGameRole.create([place: '軍事基地', name: '逃兵'])
    SpyGameRole.create([place: '軍事基地', name: '上校'])
    SpyGameRole.create([place: '軍事基地', name: '士兵'])
    SpyGameRole.create([place: '軍事基地', name: '醫護兵'])
    SpyGameRole.create([place: '軍事基地', name: '狙擊手'])
    SpyGameRole.create([place: '軍事基地', name: '坦克工兵'])
    SpyGameRole.create([place: '軍事基地', name: '指揮官'])

    SpyGameRole.create([place: '電影工作室', name: '替身演員'])
    SpyGameRole.create([place: '電影工作室', name: '音控師'])
    SpyGameRole.create([place: '電影工作室', name: '攝影師'])
    SpyGameRole.create([place: '電影工作室', name: '導演'])
    SpyGameRole.create([place: '電影工作室', name: '服裝師'])
    SpyGameRole.create([place: '電影工作室', name: '演員'])
    SpyGameRole.create([place: '電影工作室', name: '製作人'])

    SpyGameRole.create([place: '夜店', name: 'DJ'])
    SpyGameRole.create([place: '夜店', name: '舞者'])
    SpyGameRole.create([place: '夜店', name: '警衛'])
    SpyGameRole.create([place: '夜店', name: '酒保'])
    SpyGameRole.create([place: '夜店', name: '喝醉的人'])
    SpyGameRole.create([place: '夜店', name: '酒客'])
    SpyGameRole.create([place: '夜店', name: '扒手'])

    SpyGameRole.create([place: '遠洋郵輪', name: '富豪'])
    SpyGameRole.create([place: '遠洋郵輪', name: '廚師'])
    SpyGameRole.create([place: '遠洋郵輪', name: '船長'])
    SpyGameRole.create([place: '遠洋郵輪', name: '酒保'])
    SpyGameRole.create([place: '遠洋郵輪', name: '音樂家'])
    SpyGameRole.create([place: '遠洋郵輪', name: '侍者'])
    SpyGameRole.create([place: '遠洋郵輪', name: '技工'])

    SpyGameRole.create([place: '火車', name: '技工'])
    SpyGameRole.create([place: '火車', name: '邊境巡邏員'])
    SpyGameRole.create([place: '火車', name: '服務生'])
    SpyGameRole.create([place: '火車', name: '乘客'])
    SpyGameRole.create([place: '火車', name: '廚師'])
    SpyGameRole.create([place: '火車', name: '工程師'])
    SpyGameRole.create([place: '火車', name: '添煤員'])

    SpyGameRole.create([place: '海盜船', name: '廚子'])
    SpyGameRole.create([place: '海盜船', name: '水手'])
    SpyGameRole.create([place: '海盜船', name: '奴隸'])
    SpyGameRole.create([place: '海盜船', name: '砲手'])
    SpyGameRole.create([place: '海盜船', name: '囚犯'])
    SpyGameRole.create([place: '海盜船', name: '妓女'])
    SpyGameRole.create([place: '海盜船', name: '勇敢的船長'])

    SpyGameRole.create([place: '極地觀測站', name: '醫護員'])
    SpyGameRole.create([place: '極地觀測站', name: '地理學家'])
    SpyGameRole.create([place: '極地觀測站', name: '探險隊長'])
    SpyGameRole.create([place: '極地觀測站', name: '生物學家'])
    SpyGameRole.create([place: '極地觀測站', name: '通訊員'])
    SpyGameRole.create([place: '極地觀測站', name: '水文學者'])
    SpyGameRole.create([place: '極地觀測站', name: '氣象學家'])

    SpyGameRole.create([place: '警察局', name: '警探'])
    SpyGameRole.create([place: '警察局', name: '律師'])
    SpyGameRole.create([place: '警察局', name: '記者'])
    SpyGameRole.create([place: '警察局', name: '犯罪心理學家'])
    SpyGameRole.create([place: '警察局', name: '檔案管理員'])
    SpyGameRole.create([place: '警察局', name: '巡查員'])
    SpyGameRole.create([place: '警察局', name: '罪犯'])

    SpyGameRole.create([place: '餐廳', name: '音樂家'])
    SpyGameRole.create([place: '餐廳', name: '女服務員'])
    SpyGameRole.create([place: '餐廳', name: '顧客'])
    SpyGameRole.create([place: '餐廳', name: '騙子'])
    SpyGameRole.create([place: '餐廳', name: '主廚'])
    SpyGameRole.create([place: '餐廳', name: '美食評論家'])
    SpyGameRole.create([place: '餐廳', name: '服務生'])

    SpyGameRole.create([place: '學校', name: '體育老師'])
    SpyGameRole.create([place: '學校', name: '學生'])
    SpyGameRole.create([place: '學校', name: '校長'])
    SpyGameRole.create([place: '學校', name: '校園警衛'])
    SpyGameRole.create([place: '學校', name: '管理員'])
    SpyGameRole.create([place: '學校', name: '午餐阿姨'])
    SpyGameRole.create([place: '學校', name: '工友'])

    SpyGameRole.create([place: '汽車維修站', name: '經理'])
    SpyGameRole.create([place: '汽車維修站', name: '輪胎專員'])
    SpyGameRole.create([place: '汽車維修站', name: '機車騎士'])
    SpyGameRole.create([place: '汽車維修站', name: '車主'])
    SpyGameRole.create([place: '汽車維修站', name: '洗車工'])
    SpyGameRole.create([place: '汽車維修站', name: '電器工'])
    SpyGameRole.create([place: '汽車維修站', name: '汽車技工'])

    SpyGameRole.create([place: '太空站', name: '工程師'])
    SpyGameRole.create([place: '太空站', name: '外星人'])
    SpyGameRole.create([place: '太空站', name: '太空遊客'])
    SpyGameRole.create([place: '太空站', name: '太空梭艦長'])
    SpyGameRole.create([place: '太空站', name: '指揮官'])
    SpyGameRole.create([place: '太空站', name: '科學家'])
    SpyGameRole.create([place: '太空站', name: '醫生'])

    SpyGameRole.create([place: '潛水艇', name: '廚師'])
    SpyGameRole.create([place: '潛水艇', name: '指揮官'])
    SpyGameRole.create([place: '潛水艇', name: '聲納探測員'])
    SpyGameRole.create([place: '潛水艇', name: '電子技師'])
    SpyGameRole.create([place: '潛水艇', name: '水手'])
    SpyGameRole.create([place: '潛水艇', name: '通訊員'])
    SpyGameRole.create([place: '潛水艇', name: '領航員'])

    SpyGameRole.create([place: '超市', name: '顧客'])
    SpyGameRole.create([place: '超市', name: '管理員'])
    SpyGameRole.create([place: '超市', name: '警衛'])
    SpyGameRole.create([place: '超市', name: '收銀員'])
    SpyGameRole.create([place: '超市', name: '試吃人員'])
    SpyGameRole.create([place: '超市', name: '屠宰師'])
    SpyGameRole.create([place: '超市', name: '倉管'])

    SpyGameRole.create([place: '劇院', name: '寄物員'])
    SpyGameRole.create([place: '劇院', name: '提詞人'])
    SpyGameRole.create([place: '劇院', name: '賣票員'])
    SpyGameRole.create([place: '劇院', name: '觀眾'])
    SpyGameRole.create([place: '劇院', name: '導演'])
    SpyGameRole.create([place: '劇院', name: '演員'])
    SpyGameRole.create([place: '劇院', name: '燈光師'])

    SpyGameRole.create([place: '大學實驗室', name: '研究生'])
    SpyGameRole.create([place: '大學實驗室', name: '教授'])
    SpyGameRole.create([place: '大學實驗室', name: '院長'])
    SpyGameRole.create([place: '大學實驗室', name: '心理學家'])
    SpyGameRole.create([place: '大學實驗室', name: '維護員'])
    SpyGameRole.create([place: '大學實驗室', name: '學生'])
    SpyGameRole.create([place: '大學實驗室', name: '管理員'])

    SpyGameRole.create([place: '動物園', name: '動物學家'])
    SpyGameRole.create([place: '動物園', name: '清潔人員'])
    SpyGameRole.create([place: '動物園', name: '遊客'])
    SpyGameRole.create([place: '動物園', name: '假扮獅子的人'])
    SpyGameRole.create([place: '動物園', name: '小孩'])
    SpyGameRole.create([place: '動物園', name: '棉花糖小販'])
    SpyGameRole.create([place: '動物園', name: '飼育員'])
  end
end
