development: &default
  adapter: 'postgis'
  encoding: 'unicode'
  database: 'board_game_development'
  host: '127.0.0.1'
  username: 'aronyu'
  password: ''
  postgis_extension: true
  schema_search_path: 'public, postgis'

test: &TEST
  <<: *default
  database: 'board_game_test'

staging: &default
  adapter: 'postgis'
  encoding: 'unicode'
  database: 'board_game_staging'
  host: 'staging.cgtmlj8zesdu.ap-northeast-1.rds.amazonaws.com'
  username: 'root'
  password: ''
  postgis_extension: true
  schema_search_path: 'public, postgis'

production:
  adapter: 'postgis'
  encoding: 'unicode'
  database: 'board_game_production'
  host: 'production.cgtmlj8zesdu.ap-northeast-1.rds.amazonaws.com'
  username: 'root'
  password: ''
  postgis_extension: true
  schema_search_path: 'public, postgis'
